# Use the MySQL base image
FROM mysql:9.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=nullbyte
ENV MYSQL_USER=nullbyteadmin
ENV MYSQL_PASSWORD=rootpassword

COPY ./scripts /docker-entrypoint-initdb.d/
COPY ./data /data/

EXPOSE 3306

CMD ["mysqld"]
